import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import { useQuery } from '@apollo/client';
import { ARTICLES_QUERY, ArticlesData } from '../../graphql/queries/articles.query';

const ArticleIndex: NextPage = () => {
  const { loading, error, data } = useQuery<ArticlesData>(ARTICLES_QUERY);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {JSON.stringify(error)}</p>;

  if (!data) return <p>No data</p>;
  const { articles } = data;

  return (
    <div className={styles.container}>
      <Head>
        <title>Strapi GraphQL Next.js(Typescript)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Article一覧
        </h1>

        {articles.map((article, index) => {
        return (
          <li key={index}>
            {article.title}{' '}
              <a>[Detail]</a>
          </li>
        );
      })}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default ArticleIndex
